name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  workflow-name:  # id of input
    description: 'Workflow name to be triggered after'
    required: false
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
