on:
  pull_request:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  trigger_job:
    runs-on: ubuntu-latest
    name: Trigger job
    steps:
      - name: Trigger step
        id: trigger
        uses: armandokun/bellbird@wtfisthis
        with:
          workflow-name: 'Not Jenkins'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
